# application configuration parameters
# save as "configurations.yml" after completing

# Socrata dataset configurations
data:
  host: ENTER SOCRATA OPEN DATA PORTAL HOSTNAME
  appToken: ENTER SOCRATA APP TOKEN
  datasetId: ENTER SOCRATA DATASET ID
  appConfigDatasetId: ENTER SOCRATA DATASET ID
  filterConfigDatasetId: ENTER SOCRATA DATASET ID
  chartConfigDatasetId: ENTER SOCRATA DATASET ID
  indicatorsConfigDatasetId: ENTER SOCRATA DATASET ID

# Mapbox and other map related configurations
map:
  tileUrl: ENTER MAPBOX TILE URL
  tileId: mapbox.light
  mapboxToken: ENTER MAPBOX TOKEN
  attribution: |
    Map data ©
    <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,
    <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>,
    Imagery © <a href="http://mapbox.com">Mapbox</a>
  defaults:
    # zoom should be numeric value
    zoom: 3
    # specify longitude, then latitude value; must be a simple array
    center:
      - 37.8
      - -96
    # height in pixels, number only
    height: 320
